const aporCodes = {
  'AG': 'Agribusiness & Agricultural Workers',
  'BA': 'Banks',
  'BP': 'BPOs & Export-Oriented Business Personnel',
  'CA': 'Civil Aviation',
  'CB': 'Customs Brokerage',
  'CM': 'Capital Market',
  'CY': 'Container Yards',
  'DC': 'Delivery personnel of cargoes',
  'DE': 'Delivery Services',
  'DO': 'Distressed OFWs',
  'ER': 'Emergency Responders',
  'FC': 'Food Chain/ Resturants',
  'FS': 'Funeral Service',
  'FF': 'Freight forwarders',
  'GE': 'Government Agency - Executive',
  'GJ': 'Government Agency - Judicial',
  'GL': 'Government Agency - Legislative',
  'GR': 'Grocery and Convenience Stores',
  'HM': 'Heads of Mission',
  'HT': 'Hotel Employees and Tenants',
  'IP': 'International Passengers and Driver',
  'LW': 'Logistics Warehouse',
  'ME': 'Media Personalities',
  'MS': 'Medical Services',
  'MF': 'Manufacturing',
  'MT': 'Money Transfer Services',
  'PH': 'Pharmacies / Drug Stores',
  'PM': 'Public Market',
  'PO': 'Port operators',
  'SA': 'Sanitation',
  'SH': 'Ship Captain & Crew',
  'SL': 'Shipping lines',
  'SS': 'Security Services',
  'TE': 'Telecommunications',
  'TF': 'Transportation Facilities',
  'TS': 'Trucking Services',
  'UT': 'Utilities',
  'VE': 'Veterinary',
  'WC': 'Water Companies',
  'WH': 'Warehousing'
};
